{{-- ==========================================================
| Purchase Order Footer
| Nexus ERP 2.0
========================================================== --}}

<style>

.document-footer{

    margin-top:35px;

    padding-top:12px;

    border-top:1px solid #d9d9d9;

    font-size:11px;

    color:#6b7280;

}

.document-footer table{

    width:100%;

    border-collapse:collapse;

}

.document-footer td{

    padding:4px 0;

    vertical-align:top;

}

.footer-left{

    text-align:left;

}

.footer-center{

    text-align:center;

}

.footer-right{

    text-align:right;
    padding-right: 20px !important;

}

.footer-note{

    margin-top:10px;

    font-style:italic;

    color:#9ca3af;

}

</style>

<div class="document-footer">

    <table>

        <tr>

            <td class="footer-center">

                <strong>Printed On</strong><br>

                {{ now()->format('d M Y H:i') }}

            </td>

            <td class="footer-right">

                <strong>Page</strong><br>

                1 of 1

            </td>

        </tr>

        <tr>

            <td class="footer-center">

                <strong>Generated by Nexus ERP 2.0</strong>

            </td>

            <td class="footer-right">

                Version 1.0

            </td>

        </tr>

    </table>

    <div class="footer-note" align="center">

        This Purchase Order is generated electronically by Nexus ERP 2.0.
        Printed copies are considered uncontrolled unless verified against the system.

    </div>

</div>