{{-- ==========================================================
| Purchase Order Footer
| Nexus ERP 2.0
| Compact Corporate Layout
========================================================== --}}

<style>

.document-footer{

    margin-top:17px;

    padding-top:6px;

    border-top:1px solid #d9d9d9;

    font-size:8px;

    line-height:1.1;

    color:#6b7280;

}

.document-footer table{

    width:100%;

    border-collapse:collapse;

}

.document-footer td{

    padding:2px 0;

    vertical-align:middle;

    line-height:1.1;

}

.footer-left{

    text-align:left;

}

.footer-center{

    text-align:center;

}

.footer-right{

    text-align:right;

    padding-right:10px !important;

}

.footer-note{

    margin-top:4px;

    font-size:6.5px;

    line-height:1.1;

    font-style:italic;

    color:#9ca3af;

    text-align:center;

}

</style>


<div class="document-footer">

    <table>

        <tr>

            <td class="footer-center">

                <strong>Printed On</strong><br>

                {{ \App\Support\Timezone\UserTimezone::now()->format('d M Y H:i') }}

            </td>

            <td class="footer-right">

                <strong>Page</strong><br>

                1 of 1

            </td>

        </tr>

        <tr>

            <td class="footer-center">

                <strong>Generated by Nexus ERP 2.0</strong>

            </td>

            <td class="footer-right">

                Version 1.0

            </td>

        </tr>

    </table>

    <div class="footer-note">

        This Purchase Order is generated electronically by Nexus ERP 2.0.
        Printed copies are considered uncontrolled unless verified against the system.

    </div>

</div>