{{-- ==========================================================
| Purchase Order Signature
| Nexus ERP 2.0
========================================================== --}}

<style>

.signature-table{

    width:100%;

    border-collapse:collapse;

    margin-top:18px;

}

.signature-table td{

    width:33.33%;

    text-align:center;

    vertical-align:top;

    padding:15px;

}

.signature-title{

    font-size:13px;

    font-weight:600;

    color:#374151;

    margin-bottom:45px;

}

.signature-line{

    border-top:1px solid #444;

    margin:0 auto;

    width:85%;

    padding-top:6px;

}

.signature-name{

    font-weight:600;

    font-size:13px;

}

.signature-position{

    font-size:12px;

    color:#6b7280;

    margin-top:2px;

}

.signature-date{

    font-size:11px;

    color:#9ca3af;

    margin-top:4px;

}


{{-- ==========================================================
| Purchase Order Signature
| Nexus ERP 2.0
| Corporate Layout
========================================================== --}}

<style>

.signature-table {

    width: 100%;

    border-collapse: collapse;

    margin-top: 18px;

    border: 1px solid #b8c3cf;

}

.signature-table td {

    width: 50%;

    text-align: center;

    vertical-align: top;

    padding: 7px 12px 12px;

    border: 1px solid #b8c3cf;

    height: 125px;

}

.signature-title {

    font-size: 13px;

    font-weight: 600;

    color: #374151;

    margin-bottom: 42px;

}

.signature-line {

    border-top: 1px solid #444;

    margin: 0 auto;

    width: 85%;

    padding-top: 5px;

}

.signature-name {

    font-weight: 600;

    font-size: 13px;

    color: #111827;

}

.signature-position {

    font-size: 11px;

    color: #6b7280;

    margin-top: 2px;

}

.signature-date {

    font-size: 11px;

    color: #9ca3af;

    margin-top: 3px;

}

</style>


<table class="signature-table">

    <tr>

        {{-- =============================================
        Prepared By
        ============================================= --}}

        <td>

            <div class="signature-title">

                Prepared By

            </div>

            <div class="signature-line">

                <div class="signature-position">

                    Generated By

                </div>

                <div class="signature-date">

                    {{ optional($purchaseOrder->generated_at)->format('d M Y H:i') }}

                </div>

                <div class="signature-name">

                    {{ $generatedBy?->name ?? '-' }}

                </div>

            </div>

        </td>


        {{-- =============================================
        Approved By
        ============================================= --}}

        <td>

            <div class="signature-title">

                Approved By

            </div>

            <div class="signature-line">

                <div class="signature-position">

                    Approver

                </div>

                <div class="signature-date">

                    {{ optional($purchaseOrder->approved_at)->format('d M Y H:i') }}

                </div>

                <div class="signature-name">

                    {{ $approvedBy?->name ?? '-' }}

                </div>

            </div>

        </td>

    </tr>

</table>
