{{-- ==========================================================
| Purchase Order Signature
| Nexus ERP 2.0
========================================================== --}}

<style>

.signature-table{

    width:100%;

    border-collapse:collapse;

    margin-top:18px;

}

.signature-table td{

    width:33.33%;

    text-align:center;

    vertical-align:top;

    padding:15px;

}

.signature-title{

    font-size:13px;

    font-weight:600;

    color:#374151;

    margin-bottom:45px;

}

.signature-line{

    border-top:1px solid #444;

    margin:0 auto;

    width:85%;

    padding-top:6px;

}

.signature-name{

    font-weight:600;

    font-size:13px;

}

.signature-position{

    font-size:12px;

    color:#6b7280;

    margin-top:2px;

}

.signature-date{

    font-size:11px;

    color:#9ca3af;

    margin-top:4px;

}


{{-- ==========================================================
| Purchase Order Signature
| Nexus ERP 2.0
| Corporate Layout
========================================================== --}}

<style>

.signature-table {

    width: 100%;

    border-collapse: collapse;

    margin-top: 18px;

    border: 1px solid #b8c3cf;

}

.signature-table td {
    padding: 5px 8px 8px;
    height: 105px;
}

.signature-title {
    font-size: 9pt;
    margin-bottom: 32px;
}

.signature-line {

    border-top: 1px solid #444;

    margin: 0 auto;

    width: 85%;

    padding-top: 5px;

}

.signature-name {
    font-size: 8.5pt;
}

.signature-position {
    font-size: 7.5pt;
}

.signature-date {
    font-size: 7.5pt;
}

</style>


<table class="signature-table">

    <tr>

        {{-- =============================================
        Prepared By
        ============================================= --}}

        <td>

            <div class="signature-title">

                Prepared By

            </div>

            <div class="signature-line">

                <div class="signature-position">

                    Generated By

                </div>

                <div class="signature-date">

                    {{ $purchaseOrder->generated_at
                        ? \App\Support\Timezone\UserTimezone::format(
                            $purchaseOrder->generated_at,
                            'd M Y H:i'
                        )
                        : '-'
                    }}

                </div>

                <div class="signature-name">

                    {{ $generatedBy?->name ?? '-' }}

                </div>

            </div>

        </td>


        {{-- =============================================
        Approved By
        ============================================= --}}

        <td>

            <div class="signature-title">

                Approved By

            </div>

            <div class="signature-line">

                <div class="signature-position">

                    Approver

                </div>

                <div class="signature-date">

                    {{ $purchaseOrder->approved_at
                        ? \App\Support\Timezone\UserTimezone::format(
                            $purchaseOrder->approved_at,
                            'd M Y H:i'
                        )
                        : '-'
                    }}

                </div>

                <div class="signature-name">

                    {{ $approvedBy?->name ?? '-' }}

                </div>

            </div>

        </td>

    </tr>

</table>
