DROP TABLE IF EXISTS `items`;

CREATE TABLE `items` (
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
`uuid` CHAR(36) NOT NULL,
`item_code` VARCHAR(50) NOT NULL,
`item_name` VARCHAR(255) NOT NULL,
`short_name` VARCHAR(100) DEFAULT NULL,
`search_name` VARCHAR(255) DEFAULT NULL,
`description` TEXT,
`category_id` BIGINT UNSIGNED DEFAULT NULL,
`brand_id` BIGINT UNSIGNED DEFAULT NULL,
`manufacturer_id` BIGINT UNSIGNED DEFAULT NULL,
`base_uom_id` BIGINT UNSIGNED NOT NULL,
`item_type` VARCHAR(50) NOT NULL DEFAULT 'Inventory',
`stock_type` VARCHAR(30) DEFAULT 'Stock',
`minimum_stock` DECIMAL(18,4) DEFAULT 0,
`maximum_stock` DECIMAL(18,4) DEFAULT 0,
`reorder_level` DECIMAL(18,4) DEFAULT 0,
`reorder_quantity` DECIMAL(18,4) DEFAULT 0,
`safety_stock` DECIMAL(18,4) DEFAULT 0,
`economic_order_qty` DECIMAL(18,4) DEFAULT 0,
`lead_time_days` INT UNSIGNED DEFAULT 0,
`default_warehouse_id` BIGINT UNSIGNED DEFAULT NULL,
`warehouse_type_id` BIGINT UNSIGNED DEFAULT NULL,
`purchase_uom_id` BIGINT UNSIGNED DEFAULT NULL,
`sales_uom_id` BIGINT UNSIGNED DEFAULT NULL,
`purchase_currency_id` BIGINT UNSIGNED DEFAULT NULL,
`sales_currency_id` BIGINT UNSIGNED DEFAULT NULL,
`inventory_account_id` BIGINT UNSIGNED DEFAULT NULL,
`expense_account_id` BIGINT UNSIGNED DEFAULT NULL,
`income_account_id` BIGINT UNSIGNED DEFAULT NULL,
`country_of_origin` VARCHAR(100) DEFAULT NULL,
`hs_code` VARCHAR(50) DEFAULT NULL,
`part_number` VARCHAR(100) DEFAULT NULL,
`model_number` VARCHAR(100) DEFAULT NULL,
`drawing_number` VARCHAR(100) DEFAULT NULL,
`revision_no` VARCHAR(30) DEFAULT NULL,
`net_weight` DECIMAL(18,4) DEFAULT 0,
`gross_weight` DECIMAL(18,4) DEFAULT 0,
`length` DECIMAL(18,4) DEFAULT 0,
`width` DECIMAL(18,4) DEFAULT 0,
`height` DECIMAL(18,4) DEFAULT 0,
`volume` DECIMAL(18,4) DEFAULT 0,
`is_serialized` TINYINT(1) DEFAULT 0,
`is_batch_tracked` TINYINT(1) DEFAULT 0,
`is_barcoded` TINYINT(1) DEFAULT 1,
`is_qrcode` TINYINT(1) DEFAULT 1,
`is_inventory` TINYINT(1) DEFAULT 1,
`is_purchase` TINYINT(1) DEFAULT 1,
`is_sales` TINYINT(1) DEFAULT 0,
`is_asset` TINYINT(1) DEFAULT 0,
`is_service` TINYINT(1) DEFAULT 0,
`is_manufacturing` TINYINT(1) DEFAULT 0,
`is_rental` TINYINT(1) DEFAULT 0,
`is_active` TINYINT(1) DEFAULT 1,
`remarks` TEXT,
`created_by` BIGINT UNSIGNED DEFAULT NULL,
`updated_by` BIGINT UNSIGNED DEFAULT NULL,
`deleted_by` BIGINT UNSIGNED DEFAULT NULL,
`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`deleted_at` TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY(`id`),UNIQUE KEY `uk_uuid`(`uuid`),UNIQUE KEY `uk_code`(`item_code`),KEY `idx_name`(`item_name`),KEY `idx_category`(`category_id`),KEY `idx_brand`(`brand_id`),KEY `idx_manufacturer`(`manufacturer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
