DROP TABLE IF EXISTS item_images;
CREATE TABLE item_images(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 item_id BIGINT UNSIGNED NOT NULL,
 image_path VARCHAR(255) NOT NULL,
 image_name VARCHAR(255),
 is_primary TINYINT(1) DEFAULT 0,
 sort_order INT DEFAULT 0,
 remarks TEXT,
 created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at TIMESTAMP NULL DEFAULT NULL,
 INDEX(item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;