DROP TABLE IF EXISTS item_barcodes;
CREATE TABLE item_barcodes(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 item_id BIGINT UNSIGNED NOT NULL,
 barcode VARCHAR(150) NOT NULL,
 barcode_type VARCHAR(30) DEFAULT 'CODE128',
 is_default TINYINT(1) DEFAULT 1,
 created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at TIMESTAMP NULL DEFAULT NULL,
 INDEX(item_id),UNIQUE(barcode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;