DROP TABLE IF EXISTS item_suppliers;
CREATE TABLE item_suppliers(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 item_id BIGINT UNSIGNED NOT NULL,
 supplier_id BIGINT UNSIGNED NOT NULL,
 supplier_item_code VARCHAR(100),
 supplier_item_name VARCHAR(255),
 is_preferred TINYINT(1) DEFAULT 0,
 lead_time_days INT DEFAULT 0,
 minimum_order_qty DECIMAL(18,4) DEFAULT 0,
 created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at TIMESTAMP NULL DEFAULT NULL,
 INDEX(item_id),INDEX(supplier_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;